[env:m5stick-c]
platform = espressif32@6.9.0
board = m5stick-c
framework = arduino
monitor_speed = 115200
upload_speed = 1500000
build_flags =
    -D CONFIG_UART_ISR_IN_IRAM=1
lib_deps =
    m5stack/M5StickC
