[env:m5stick-c]
platform = espressif32@6.9.0
board = m5stick-c
framework = arduino
monitor_speed = 115200
upload_speed = 1500000
build_flags =
    -D BOARD_M5STICKC=1
    -D PIN_TXD=32
    -D PIN_RXD=33

[env:m5stack-atoms3]
platform = espressif32@6.9.0
board = m5stack-atoms3
framework = arduino
monitor_speed = 115200
upload_protocol = esptool
board_upload.use_1200bps_touch = yes
board_upload.wait_for_upload_port = yes
build_flags =
    -D BOARD_ATOMS3=1
    -D PIN_TXD=2
    -D PIN_RXD=1
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
